- apps/explorer/src/components/network/Network.tsx
- apps/explorer/src/ui/header/NetworkSelect.tsx
- apps/explorer/src/utils/api/DefaultRpcClient.ts
- apps/explorer/tailwind.config.ts
- sdk/typescript/src/client/network.ts
frontend: 
before 
after 
backend: 
testnet, devnet sending the correct request to dWallet full node via RPC
> explorer: Fixed Testnet and Devnet menu route to dWallet rpc and change sizing of the textbox

- crates/sui-framework/Makefile
- crates/sui-framework/packages/dwallet-system/sources/dwallet.move
- crates/sui-framework/packages/dwallet-system/sources/dwallet_2pc_mpc_ecdsa_k1.move
- crates/sui-framework/packages/dwallet-system/tests/dwallet_ecdsa_k1_tests.move
- crates/sui-framework/packages/dwallet-system/tests/dwallet_tests.move
test cases added:
test_create_dkg_session
test_create_dkg_output
test_create_dkg_output_not_system_address
> `dwallet-network`: added test module for `dwallet_2pc_mpc_ecdsa_k1` move module

- docs/docs/developers-guide/getting-started/encryption-key.md
- docs/docs/developers-guide/getting-started/user-share-encryption.md
- docs/docs/developers-guide/getting-started/your-first-dwallet.md
- docs/sidebars.js
1. Updating the dWallet Creation steps
2. Introducing the concept of Encryption Keys
3. Using Encryption Keys for User Secret Share encryption and transfer.
> Docs - User Secret Share Encryption

- crates/pera-core/src/dwallet_mpc/mod.rs
- crates/pera-core/src/dwallet_mpc/mpc_manager.rs
> fix: Decrease the party ID by 1 when mapping it back to the public key

- crates/ika-core/src/consensus_handler.rs
I forgot to remove this scenario while implementing https://github.com/dwallet-labs/dwallet-network/pull/749
> fix: Remove malicious actors flagging while processing outputs during a state sync

- crates/dwallet-mpc-types/src/dwallet_mpc.rs
- crates/ika-core/src/dwallet_mpc/README.md
- crates/ika-core/src/dwallet_mpc/mod.rs
- crates/ika-core/src/dwallet_mpc/mpc_session.rs
- crates/ika-types/src/committee.rs
- crates/ika-types/src/messages_consensus.rs
Has been taken from Cyprien's audit [here](https://github.com/dwallet-labs/dwallet-network/pull/591)
> chore: Minor refactors and documentation fixes

- crates/ika-core/src/dwallet_mpc/malicious_handler.rs
Has been accidentally removed in [this pr](https://github.com/dwallet-labs/dwallet-network/pull/756/files)
> fix: Mark malicious parties has malicious

- Cargo.lock
- crates/ika-core/src/dwallet_mpc/cryptographic_computations_orchestrator.rs
- crates/ika-core/src/dwallet_mpc/mpc_manager.rs
- crates/ika-core/src/runtime.rs
- crates/ika-node/Cargo.toml
- crates/ika-node/src/lib.rs
Reverts dwallet-labs/dwallet-network#819
> Revert "feat: Configure the size of the Rayon & Tokio thread pools"

- crates/ika-core/src/authority/authority_per_epoch_store.rs
- crates/ika-core/src/dwallet_mpc/cryptographic_computations_orchestrator.rs
- crates/ika-core/src/dwallet_mpc/dwallet_mpc_metrics.rs
- crates/ika-core/src/dwallet_mpc/dwallet_mpc_service.rs
- crates/ika-core/src/dwallet_mpc/mod.rs
- crates/ika-core/src/dwallet_mpc/mpc_manager.rs
- crates/ika-core/src/dwallet_mpc/mpc_outputs_verifier.rs
- crates/ika-core/src/sui_connector/metrics.rs
- crates/ika-core/src/sui_connector/sui_executor.rs
- crates/ika-node/src/lib.rs
This PR add validator metrics as has been specified in [this document](https://dwalletlabs.slack.com/docs/T03RSJCFQKV/F08R0NQEHAR). Note that the notifier metrics are not yet implemented in this pr.
> chore: Add metrics for DWallet MPC operations

- crates/ika-move-packages/packages/ika_system/sources/system/system_inner.move
Fixes function `get_reporters_of` since it uses itself instead of `validator_set`
Please use lint to fix lint of the file.
> fix: get reporters of 

- crates/ika-core/src/dwallet_mpc/crytographic_computation/orchestrator.rs
- crates/ika-core/src/dwallet_mpc/mpc_session.rs
- crates/ika-node/src/lib.rs
> chore: Add context to dWallet MPC logs

- crates/ika-core/src/dwallet_mpc/crytographic_computation/orchestrator.rs
- crates/ika-core/src/dwallet_mpc/dwallet_mpc_metrics.rs
> chore: Add computation average & session start count metrics

- crates/ika-core/Cargo.toml
- crates/ika-core/src/dwallet_mpc/dwallet_mpc_metrics.rs
- pnpm-lock.yaml
> chore: Add variance metric

- crates/ika-core/src/dwallet_mpc/crytographic_computation/orchestrator.rs
> fix: Stop using all machine cores to perform cryptographic computations

- sdk/typescript/src/dwallet-mpc/dkg.ts
> chore: Fix TS CI

- crates/ika-core/src/dwallet_mpc/mpc_event.rs
- crates/ika-core/src/dwallet_mpc/mpc_manager.rs
- crates/ika-core/src/sui_connector/sui_executor.rs
- crates/ika-sui-client/src/lib.rs
> chore: Convert Sui Client internal error logs to warn

- crates/dwallet-mpc-centralized-party/src/lib.rs
- pnpm-lock.yaml
- sdk/dwallet-mpc-wasm/src/lib.rs
- sdk/typescript/test/e2e/dwallet-mpc.test.ts
I ran a local network & ran all the modified tests against it.
---
> test: Add signature verification to sign e2e tests

- sdk/typescript/src/dwallet-mpc/globals.ts
- sdk/typescript/src/dwallet-mpc/network-dkg.ts
- sdk/typescript/test/e2e/dwallet-mpc.test.ts
> chore: Create a TS test that creates a network key by cap

- sdk/typescript/test/chaos-test/README.md
- sdk/typescript/test/chaos-test/chaos.test.ts
> test: Update the existing chaos tests to use the new SDK

- pnpm-lock.yaml
- sdk/typescript/package.json
- sdk/typescript/test/cryptography/direct-functions.test.ts
- sdk/typescript/test/helpers/dwallet-test-helpers.ts
- sdk/typescript/test/helpers/shared-test-setup.ts
- sdk/typescript/test/helpers/test-utils.ts
- sdk/typescript/test/ika-client/basic-features.test.ts
- sdk/typescript/test/ika-transaction/non-transfer-methods.test.ts
- sdk/typescript/test/ika-transaction/secret-share-methods.test.ts
- sdk/typescript/test/imported-dwallet/creating-imported-dwallet.test.ts
- sdk/typescript/test/imported-dwallet/imported-dwallet-sharing.test.ts
- sdk/typescript/test/imported-dwallet/imported-dwallet-sign.test.ts
- sdk/typescript/test/multiple-network-keys/multiple-network-keys.test.ts
- sdk/typescript/test/network-config/configuration.test.ts
- sdk/typescript/test/shared-dwallet/dwallet-sharing-sign.test.ts
- sdk/typescript/test/shared-dwallet/dwallet-sharing.test.ts
- sdk/typescript/test/shared-dwallet/re-encrypted-dwallet.test.ts
- sdk/typescript/test/shared-dwallet/shared-imported-sign.test.ts
- sdk/typescript/test/unit/errors.test.ts
- sdk/typescript/test/unit/index.test.ts
- sdk/typescript/test/unit/user-share-encryption-keys.test.ts
- sdk/typescript/test/unit/utils.test.ts
- sdk/typescript/test/zero-trust-dwallet/creating-dwallet.test.ts
- sdk/typescript/test/zero-trust-dwallet/dwallet-future-sign.test.ts
- sdk/typescript/test/zero-trust-dwallet/dwallet-sign.test.ts
- sdk/typescript/vitest.config.ts
since we need a lot more ram in our nodejs process, i suggest you guys to test it with this: `NODE_OPTIONS=--max-old-space-size=8192 pnpm vitest run`, i know it is crazy... let me know if you guys see any optimizations can be done
> cover all cases

- sdk/typescript/examples/common.ts
- sdk/typescript/examples/zero-trust-dwallet/creating-dwallet.ts
- sdk/typescript/src/client/ika-transaction.ts
- sdk/typescript/src/tx/coordinator.ts
- sdk/typescript/test/helpers/dwallet-test-helpers.ts
- sdk/typescript/test/helpers/shared-test-setup.ts
- sdk/typescript/test/ika-transaction/secret-share-methods.test.ts
- sdk/typescript/test/zero-trust-dwallet/dwallet-sign.test.ts
while checking the code before hand, i saw that we need more composability around capabilities, espically on dWalletCap and partialUserSignatureCap sides, i added more composability into this in the SDK, and all tests are passing.
> more composability

- crates/dwallet-mpc-centralized-party/src/lib.rs
- sdk/ika-wasm/Cargo.lock
- sdk/ika-wasm/src/lib.rs
> chore: Fix CI

- sdk/typescript/package.json
- sdk/typescript/src/client/ika-client.ts
- sdk/typescript/src/client/types.ts
this PR requires @omersadika to publish the new version of the SDK once merged
> feat: add sign object fetching and fix postinstall - main
